### ISSUE TITLE
Fix GitHub Actions for not deploying every Lando PHP image to Dockerhub

### ISSUE THREAD

**Issue by kaszarobert** [lando/php#98]
https://github.com/lando/php/issues/77#issuecomment-1943963779:
> It looks like something is not right in github actions file. It seems like it's only building php 7.3 https://github.com/lando/php/actions/runs/7186820860/job/19573056931
> 
> As you can see https://hub.docker.com/r/devwithlando/php/tags?page=1&name=7.3 is updated a few hours ago, but https://hub.docker.com/r/devwithlando/php/tags?page=1&name=8.2 is updated 9 months ago, and 8.3 is not in there.

**Comment by tvlooy** [comment]
@kaszarobert I made an attempt to fix this. I suppose it's not exactly the best way, or like it was intended in github actions but this seems to work and could be a good workaround for now.

**Comment by tvlooy** [comment]
I referenced the commit that I think introduced the problem.

**Comment by reynoldsalec** [comment]
@tvlooy you're totally right, the build matrix is the root of the problem here. I think I'm just going to hardcode the `lando-version` right now; I tried a few variations on the build matrix and wasn't able to find a way to do include it in there (other than doing what you did, repeat it across all the `include` items). You can see my approach (and a fix for those broken 8.3 builds) here if you're interested: https://github.com/lando/php/pull/101/files

Thanks for flagging this and finding the issue @tvlooy!

**Comment by tvlooy** [comment]
Thanks so much! 👍
